### ISSUE TITLE
Not working with PHP< 8.0

### ISSUE THREAD

**Issue by edersonRB** [marvinlabs/laravel-discord-logger#52] opened 2024-01-25 04:46 UTC
I was running into a problem with the package in a project using php 7.4. The issue was due to union types which is only supported after 8, so changing the union type to an untyped parameter on the "write" function in the 39th line of "LogHandler.php" file woud not change functionality and makes the package compatible with older versions of PHP (not sure how old)

**Comment by vpratfr** [comment] 2024-01-25 08:00
Duplicate of #45 

See also https://github.com/marvinlabs/laravel-discord-logger/pull/46#issuecomment-1783518631

**Closed by vpratfr** 2024-01-25 08:00 UTC
